
# Python ile veri analizi (data analysis with python )



 # Numpy
 Pandas
 Veri Görselleştirme : Matplotlip & Seaborn
 Gelişmiş Fonksiyonel Keşifçi Veri Analizi (advanced functional exploratory data analysis )


 NUMPY

*  Neden Numpy? (Why Numpy?) -> matris ve diziler hesaplanır / daha az çaba ile daha fazla işlem
 * NumPy Array'i oluşturmak (Creating Numpy Array)
 * Numpy Array Özellikleri (Attributes of Numpy Array)
 * Yeniden Şekillendirme (Reshaping)
 * Index Secimi (Index Selection)
 * Slicing
 * Fancy Index
 * Numpy'da Koşullu İşlemler (Conditons on Numpy)
 * Matematiksel İşlemler (Mathematical Operations)

 neden numpy ?
 * 1 hız sabit tipte veri tutarak gerçekleştiriyor
 * 2 vektörel seviyeden yani daha az eforla daha fazla işlem yapıyor


In [1]:
import numpy as np
a = [1,2,3,4]
b = [2,3,4,5]

ab = []

In [7]:
for i in range(0, len(a)):
    ab.append(a[i] * b[i])

# numpy da bu yöntem şöyle olur

a = ([1,2,3,4])
b = ([2,3,4,5]) 


Numpy Array'i oluşturmak (Creating Numpy Arrays)

In [8]:
np.array([1,2,3,4,5])
type(np.array([1,2,3,4,5]))
np.zeros(10,dtype=int)
np.random.randint(0,10, size=10) # -> 0 ile 10 arasında rastgele 10 tane değer döndür 

array([0, 1, 9, 9, 0, 8, 9, 8, 4, 9])

In [12]:
np.random.normal(10,4,(3,4)) # -> ortalaması 10 standard sapması 4 olan 3/4 lük bir aray oluştur

array([[16.17513215, 11.35706061, 12.43721158,  4.46266333],
       [ 8.8692202 , 10.41863415, 11.3576736 ,  8.90187836],
       [14.79028551, 14.47352412,  6.87527542, 11.60249535]])

Numpy Array Özellikleri ( Attributes of Numpy Arrays)  

* ndim : boyut sayısı 
* shape : boyut bilgisi 
* size : toplam eleman sayısı 
* dtype : array veri tipi 

In [15]:
a = np.random.randint(10,size = 5)

In [16]:
a

array([6, 9, 6, 2, 5])

In [18]:
a.ndim # kaç boyutlu 1 mi 2 mi dizi

1

In [19]:
a.shape # boyut sayısı satır ve sütun

(5,)

In [20]:
a.size # boyutunu öğrenmek için

5

In [21]:
a.dtype # tipini öğrenmek için

dtype('int32')

Yeniden Şekillendirme ( Reshaping ) 

In [22]:
np.random.randint(1,10,size = 9)

array([5, 9, 8, 4, 3, 1, 6, 1, 1])

3x3 lük bir matrise çevirmek istiyoruz

In [23]:
np.random.randint(1,10,size = 9).reshape(3,3) # kalıcı tutulmuyor

array([[1, 5, 2],
       [1, 8, 1],
       [3, 3, 8]])

In [24]:
# 2 yöntem 

ar = np.random.randint(1,10,size = 9)

In [25]:
ar.reshape(3,3)

array([[7, 8, 6],
       [1, 8, 7],
       [5, 9, 4]])

Index seçimi (index selection)

In [26]:
a = np.random.randint(10, size=10)

In [27]:
a

array([5, 4, 6, 0, 3, 2, 6, 0, 1, 9])

In [28]:
a[0]

5

In [29]:
a[0:5] # -> slicing / dilimleme

array([5, 4, 6, 0, 3])

In [30]:
# 0 ncı elemanı değiştirmek istediğimizde 

In [31]:
a[0] = 999

In [32]:
a

array([999,   4,   6,   0,   3,   2,   6,   0,   1,   9])

In [33]:
# 2 boyutlu arrayde seçim

In [34]:
m = np.random.randint(10,size = (3,5))

In [35]:
m

array([[1, 0, 3, 2, 0],
       [3, 1, 7, 2, 1],
       [3, 3, 6, 5, 4]])

In [36]:
m[0,0]

1

In [37]:
m[1,1]

1

In [40]:
m[2,3] # -0|
       #  --1 | 
       # 5 --- 2| 

5

In [41]:
m[2,3] = 999

In [42]:
m

array([[  1,   0,   3,   2,   0],
       [  3,   1,   7,   2,   1],
       [  3,   3,   6, 999,   4]])

In [46]:
# int yerine float ifade eklemek istersek ekleyemeyiz tek bir tip bilgisi tutar diğer değerlerle uyumlu olması gerekir 

In [44]:
m[2,3] = 2.9

In [45]:
m

array([[1, 0, 3, 2, 0],
       [3, 1, 7, 2, 1],
       [3, 3, 6, 2, 4]])

In [49]:
m[:,0] # bütün satırları seç 0.sütunu seç 

array([1, 3, 3])

In [50]:
m[1,:] # 1.satır tüm sütun

array([3, 1, 7, 2, 1])

In [52]:
m[0:2,0:3] # aralık

array([[1, 0, 3],
       [3, 1, 7]])

Fancy Index 

In [56]:
v = np.arange(0,30,3) # 0 dan 30 a kadar 3 er 3 er 30 hariç

In [57]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [58]:
v[1]

3

In [59]:
# fancy index bize kolay bir şekilde seçim imkanı sunar

In [60]:
catch = [1,2,3] 
v[catch]

array([3, 6, 9])

Numpy'da koşullu işlemler (conditions on Numpy) 

In [62]:
t = np.array([1,2,3,4,5])

In [63]:
t

array([1, 2, 3, 4, 5])

In [64]:
# 3 den küçük olanları seç

In [69]:
# yöntem 1 

for i in t : 
    print(i)

1
2
3
4
5


In [76]:
ab = []
for i in t: 
    if i < 3 : 
        ab.append(i)

In [77]:
ab

[1, 2]

In [80]:
# yöntem 2 numpy ile yapma 
t<3 
t[t<3]

array([1, 2])

In [82]:
t[t>3]
t[t!=3]
t[t==3] 
t[t>=3] 

array([3, 4, 5])

Matemeatiksel İşlemler (Mathematical Operations) 

In [83]:
t = np.array([1,2,3,4,5])

In [84]:
v / 5

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [85]:
v * 5 / 10

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5])

In [86]:
v ** 2

array([  0,   9,  36,  81, 144, 225, 324, 441, 576, 729], dtype=int32)

In [87]:
v - 1 

array([-1,  2,  5,  8, 11, 14, 17, 20, 23, 26])

In [88]:
v + 1

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [89]:
# methodlar aracılığıyla yapma 

np.subtract(t,1) 
np.add(t,1) 
np.mean(t)
np.sum(t) 
np.min(t) 
np.max(t) 
np.var(t) 

2.0

In [90]:
np.subtract(t,1) 

array([0, 1, 2, 3, 4])

In [91]:
np.add(t,1) 

array([2, 3, 4, 5, 6])

In [92]:
np.mean(t)

3.0

In [93]:
np.sum(t) 

15

In [94]:
np.min(t) 

1

In [95]:
np.max(t) 


5

In [96]:
np.var(t) 

2.0

 Numpy ile iki bilinmeyenli denklem çözümü

In [97]:
# 5*x0 + x1 = 12 
# x0 + 3*x1 = 10 

In [98]:
a = np.array([[5,1],[1,3]]) 
b = np.array([12,10])  

np.linalg.solve(a,b)

array([1.85714286, 2.71428571])